### ISSUE TITLE
Cannot print schema with dynamically added Global ID field in 10.x

### ISSUE THREAD

**Issue by rtymchyk** [rmosolgo/graphql-ruby#3434]
**Describe the bug**

Printing the schema via `GraphQL::Schema::Printer.print_schema(ApiSchema)` raises error:
```
NoMethodError: undefined method `visible?' for nil:NilClass
from /gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:1442:in `visible?'
```

I've nailed it down to this `GraphQL::Define::AssignGlobalIdField.call(type_defn, :id)` (see below).

I can query for the `id` field fine, however printing causes an error where `type_class` is `nil` on the field, so the `visible?` check fails.

**Versions**

`graphql` version: 1.10.12
`rails` (or other framework): 6.0.3.6

**GraphQL schema**

Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? No

```ruby
# frozen_string_literal: true
class BaseObject < GraphQL::Schema::Object
  include ApolloFederation::Object

  field_class BaseField

  def current_user
    context[:current_user]
  end

  def self.model(model_class = nil)
    if model_class
      @model_class = model_class
    else
      @model_class
    end
  end

  def self.to_graphql
    type_defn = super

    if @model_class
      unless type_defn.interfaces.include?(GraphQL::Relay::Node.interface)
        type_defn.interfaces = type_defn.interfaces + [GraphQL::Relay::Node.interface]
      end

      GraphQL::Define::AssignGlobalIdField.call(type_defn, :id)
    end

    type_defn
  end
end

```
**Steps to reproduce**

Add field dynamically as above. Print schema.

**Expected behavior**

Prints string.

**Actual behavior**

```
NoMethodError: undefined method `visible?' for nil:NilClass
from /gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:1442:in `visible?'
```

Note that the trace below is triggered by `apollo-federation`s `federation_sdl`, however internally that uses the built-in schema printer as I noticed above.
<details>
<summary>Click to view exception backtrace</summary>

```
/gem_bag/ruby/2.7.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
/gem_bag/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
/gem_bag/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
/gem_bag/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
/gem_bag/ruby/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
/gem_bag/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:527:in `call'
<redacted>/lib/downcase_route_middleware.rb:14:in `call'
/gem_bag/ruby/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/rack/capture_exceptions.rb:14:in `call'
/gem_bag/ruby/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry-ruby.rb:147:in `with_scope'
/gem_bag/ruby/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/hub.rb:52:in `with_scope'
/gem_bag/ruby/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/rack/capture_exceptions.rb:23:in `block in call'
/gem_bag/ruby/2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/static.rb:126:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/gem_bag/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/gem_bag/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/rack/logger.rb:26:in `call'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/tagged_logging.rb:80:in `tagged'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/gem_bag/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/rack/logger.rb:26:in `block in call'
/gem_bag/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/rack/logger.rb:37:in `call_app'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:101:in `run_callbacks'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/gem_bag/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:567:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/gem_bag/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/gem_bag/ruby/2.7.0/gems/clearance-2.2.1/lib/clearance/rack_session.rb:23:in `call'
/gem_bag/ruby/2.7.0/gems/sentry-rails-4.3.3/lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/route_set.rb:834:in `call'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/journey/router.rb:32:in `serve'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/journey/router.rb:32:in `each'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal.rb:254:in `dispatch'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal.rb:190:in `dispatch'
/gem_bag/ruby/2.7.0/gems/actionview-6.0.3.6/lib/action_view/rendering.rb:39:in `process'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/abstract_controller/base.rb:136:in `process'
/gem_bag/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb:180:in `instrument'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb:180:in `block in instrument'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:139:in `run_callbacks'
/gem_bag/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/abstract_controller/base.rb:195:in `process_action'
/gem_bag/ruby/2.7.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
<redacted>/controllers/graphql_controller.rb:16:in `execute'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:1612:in `execute'
/gem_bag/ruby/2.7.0/gems/graphql-persisted_queries-1.2.0/lib/graphql/persisted_queries/schema_patch.rb:26:in `multiplex'
/gem_bag/ruby/2.7.0/gems/graphql-persisted_queries-1.2.0/lib/graphql/persisted_queries/multiplex_resolver.rb:15:in `resolve'
/gem_bag/ruby/2.7.0/gems/graphql-persisted_queries-1.2.0/lib/graphql/persisted_queries/multiplex_resolver.rb:44:in `perform_multiplex'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:1641:in `multiplex'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:49:in `run_all'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:68:in `trace'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:84:in `call_tracers'
/gem_bag/ruby/2.7.0/gems/elastic-apm-3.6.0/lib/elastic_apm/graphql.rb:36:in `trace'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:84:in `block in call_tracers'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:82:in `call_tracers'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:196:in `block in instrument_and_analyze'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:83:in `map'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/multiplex.rb:113:in `begin_query'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:31:in `begin_query'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:68:in `trace'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:84:in `call_tracers'
/gem_bag/ruby/2.7.0/gems/elastic-apm-3.6.0/lib/elastic_apm/graphql.rb:36:in `trace'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:84:in `block in call_tracers'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:82:in `call_tracers'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:85:in `resolve_selection'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:85:in `each'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:128:in `resolve_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:68:in `trace'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:84:in `call_tracers'
/gem_bag/ruby/2.7.0/gems/elastic-apm-3.6.0/lib/elastic_apm/graphql.rb:35:in `trace'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:84:in `block in call_tracers'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/tracing.rb:82:in `call_tracers'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/execution/execute.rb:321:in `call'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/field.rb:136:in `resolve'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/member/instrumentation.rb:80:in `call'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/member/instrumentation.rb:80:in `call'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:521:in `resolve_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:112:in `after_lazy'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:527:in `block in resolve_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:112:in `after_lazy'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:537:in `block (2 levels) in resolve_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:709:in `public_send_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:734:in `with_extensions'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:721:in `block in public_send_field'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/field.rb:721:in `public_send'
/gem_bag/ruby/2.7.0/gems/apollo-federation-1.1.5/lib/apollo-federation/service_field.rb:22:in `_service'
/gem_bag/ruby/2.7.0/gems/apollo-federation-1.1.5/lib/apollo-federation/schema.rb:21:in `federation_sdl'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/language/document_from_schema_definition.rb:41:in `document'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/language/document_from_schema_definition.rb:250:in `build_definition_nodes'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:83:in `reachable_types'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:324:in `reachable_type_set'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:122:in `fields'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:266:in `block in read_through'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:121:in `block in fields'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:121:in `select'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:121:in `each'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:121:in `each_value'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:121:in `block (2 levels) in fields'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:170:in `visible_field?'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:262:in `visible?'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:266:in `block in read_through'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema/warden.rb:51:in `block in initialize'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/filter.rb:12:in `call'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/filter.rb:32:in `call'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/filter.rb:32:in `call'
/gem_bag/ruby/2.7.0/gems/graphql-1.10.12/lib/graphql/schema.rb:1442:in `visible?'
undefined method `visible?' for nil:NilClass
```
</details>

**Comment by rtymchyk** [comment]
I suppose I could add a new type like this below, but would rather re-use my `BaseObject` to handle this.
```
class ModelObject < BaseObject
  implements GraphQL::Types::Relay::Node

  global_id_field :id
end
```

**Comment by rmosolgo** [comment]
Interesting! GraphQL-Ruby assumes that, in a class-based schema, every legacy-style will have a corresponding class-based field (https://github.com/rmosolgo/graphql-ruby/blob/e291b702128a6088c21b67b416fb86abee73078a/lib/graphql/schema.rb#L1441-L1443). That's not the case in the example you shared above, because when object types generate their legacy-style types (in `self.to_graphql`, they add fields to the legacy types that _aren't_ in the class-based type. 


In recent graphql-ruby versions, I would expect it to work fine to include the interface and define the field in the _base type_ itself, like this: 

```ruby 
# not sure if this works in graphql-ruby 1.10.12
class BaseObject < GraphQL::Schema::Object
  # Add this interface and field to all subclasses:
  implements GraphQL::Types::Relay::Node
  global_id_field :id
end
```

If that doesn't work, you could use `self.inherited` to do the same thing: 

```ruby 
class BaseObject < GraphQL::Schema::Object 
  def self.inherited(child_class)
    child_class.implements(GraphQL::Types::Relay::Node)
    child_class.global_id_field(:id)
  end 
end 
```

Then, you could remove the id- and node-related code from `def self.to_graphql`. 

Does one of those approaches work for you?

**Comment by rtymchyk** [comment]
@rmosolgo The idea behind the `to_graphql` was to handle types like this:
```ruby
class UserType < BaseObject
  model User
```
Note that `model` setter triggers adding the `id` field later in `to_graphql`. Not all of my types are AR model based, so those that aren't don't need the ID field or the Node interface.

It sounds like if I want this selective behaviour, I instead need to do something like `class UserType < ModelType` and define as https://github.com/rmosolgo/graphql-ruby/issues/3434#issuecomment-819641241?

**Comment by rmosolgo** [comment]
How about adding the Node- and id- related stuff inside `def self.model`, for example: 

```ruby 
def self.model(model_class = nil)
  if model_class
    global_id_field :id 
    implements GraphQL::Types::Relay::Node 
  end 
  # ...
end 
```

? 

That way, any object type which has a `model` configured will also have the `id` field and `Node` interface, and you can be sure that the class-based definition and legacy definition will be in sync.

**Comment by rtymchyk** [comment]
@rmosolgo Thanks, will give that a shot. Seems obvious now that you mentioned it 😄

**Comment by rmosolgo** [comment]
Hope it helps! 

🎵 "Everything seems obvious / when someone else explains it!" 🎵  😆 

https://youtu.be/p-pJ51N2TTQ?t=161
