### ISSUE TITLE
GraphQL broken on Ruby 2.5.5

### ISSUE THREAD

**Issue by adaosantos** [rmosolgo/graphql-ruby#4007]
**Describe the bug**

**Versions**

`graphql` version: 1.13.17
`rails` (or other framework): 5.1.7

**Steps to reproduce**

1. Create a new application
2. Add the gem
3. Create new Schema
4. Run application

**Expected behavior**

Work's

**Actual behavior**

<img width="921" alt="image" src="https://user-images.githubusercontent.com/4481171/160196334-a15fd5ac-99c6-418d-964b-a71d710751e9.png">
<details>
<summary>Click to view exception backtrace</summary>
```
Traceback (most recent call last):
        33: from bin/rails:9:in `<main>'
        32: from bin/rails:9:in `require'
        31: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
        30: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
        29: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
        28: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        27: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        26: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        25: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:96:in `perform'
        24: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        23: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/command/actions.rb:15:in `require'
        22: from /mnt/wsl/PHYSICALDRIVE2/Projects/nexaas/nexaas-estoka/config/application.rb:8:in `<top (required)>'
        21: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
        20: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
        19: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
        18: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
        17: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
        16: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        15: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
        14: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql.rb:113:in `<top (required)>'
        13: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql.rb:113:in `require'
        12: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema.rb:51:in `<top (required)>'
        11: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema.rb:51:in `require'
        10: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:4:in `<top (required)>'
         9: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:5:in `<module:GraphQL>'
         8: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:23:in `<class:Schema>'
         7: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:25:in `<class:RelayClassicMutation>'
         6: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/mutation.rb:71:in `field'
         5: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/resolver/has_payload_type.rb:54:in `field'
         4: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/member/has_fields.rb:12:in `field'
         3: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:129:in `from_options'
         2: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:129:in `new'
         1: from /home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/member/accepts_definition.rb:154:in `initialize'
/home/adao/.asdf/installs/ruby/2.5.9/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
```

</details>

**Additional context**

This error is related of this PR [3856](https://github.com/rmosolgo/graphql-ruby/pull/3856) on `lib/graphql/schema/field.rb:214`  if I remove the new parameter and your references or change your position to the end of parameter lists it's work's normally

**Comment by rmosolgo** [comment]
Thanks for the detailed report! This sounds like a duplicate of https://github.com/rmosolgo/graphql-ruby/issues/3887. Apparently Ruby 2.5 had a bug where it didn't properly handle methods with more than 32 arguments. By chance, a [later PR](https://github.com/rmosolgo/graphql-ruby/pull/3917) removed some arguments to that method, so it _should_ work on GraphQL-Ruby 2.0. How about using that version?

**Comment by rmosolgo** [comment]
I don't have plans to work further on this, but if neither updating Ruby nor updating GraphQL-Ruby works for you, let me know and maybe we can find a monkey-patch that will work :+1
