### ISSUE TITLE
Behaviour of InputObjects changed after 1.10.0pre1

### ISSUE THREAD

**Issue by celsworthtf** [rmosolgo/graphql-ruby#2688]
At some point after 1.10.0pre1, the behaviour I'm seeing in InputObjects and nested loads changed.

Given this mutation:

```ruby
class Schema
  module Mutations
    class Test < GraphQL::Schema::RelayClassicMutation
      argument :attributes, Inputs::TestAttributes, required: true

      type Boolean

      def resolve(attributes:)
        p attributes
        p attributes.class

        true
      end
    end
  end
end
```

And this input object:

```ruby
class Schema
  module Inputs
    class TestAttributes < GraphQL::Schema::InputObject
      argument :person_id, ID, required: true, loads: Types::Person
    end
  end
end
```

I see this output, changing only the graphql gem version;

```
1.10.0:
{:person=>"bdd92dbb-85e4-4ad6-8711-e0c95023d588"}
Hash

1.10.0.pre2:
{:person=>"e8e2096d-3d5f-44d3-ac50-adbbafbeed2d"}
Hash

1.10.0.pre1:
#<Schema::Inputs::TestAttributes:0x00007fbf708ce650 @context=#<Query::Context ...>, @arguments=#<#<Class:0x00007fbf70b8be60>:0x00007fbf708ce5d8 … snip >
Schema::Inputs::TestAttributes
```

So pre1 works fine, giving me the expected object type (I snipped it out but it does call `object_from_id` and loads the `Person` as well), but at pre2 and in release, its being converted to a Hash for me, and not doing the `loads:` either. Is this a regression?

Let me know if you need a more self-contained example, this is just bits extracted from my current app to try and demonstrate the problem. But it's inheriting from all the native base objects, nothing of my own, so I'm not sure if anything deeper would help any.

**Comment by celsworthtf** [comment]
I've made a fully self-contained example to demonstrate this.

```ruby
#! /usr/bin/ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '1.10.0.pre1' # ok
  # gem 'graphql', '1.10.0.pre2' # breaks
  # gem 'graphql', '1.10.0' # breaks
end

class Person
  attr_accessor :id
end

class PersonType < GraphQL::Schema::Object
  field :id, ID, null: false
end

class TestAttributes < GraphQL::Schema::InputObject
  argument :person_id, ID, required: true, loads: PersonType
end

class TestMutation < GraphQL::Schema::RelayClassicMutation
  argument :attributes, TestAttributes, required: true

  type Boolean

  def resolve(attributes:)
    p attributes
    p attributes.class
    p attributes.person.id

    true
  end
end

class MutationRoot < GraphQL::Schema::Object
  field :test_mutation, mutation: TestMutation
end

class QueryRoot < GraphQL::Schema::Object
end

class Schema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  mutation MutationRoot
  query QueryRoot

  def self.object_from_id(node_id, _ctx)
    Person.new.tap { |p| p.id = node_id }
  end
end

Schema.execute(query: 'mutation($input: TestMutationInput!) { testMutation(input: $input) }',
               variables: { input: { attributes: { personId: 1 } } })
```

Just change the uncommented gem line to see the differences in behaviour.

**Comment by celsworthtf** [comment]
To narrow this down further, I git bisected and got the following:

```
5932ef3fc8c9d26df1fb597a977093dcd9fb16ab is the first bad commit
commit 5932ef3fc8c9d26df1fb597a977093dcd9fb16ab
Author: Robert Mosolgo <rdmosolgo@gmail.com>
Date:   Wed Jul 17 11:20:23 2019 -0400

    Update more runtime stuff

:040000 040000 f8aa4264a155744b8b7167130987ed30384b4241 2a97058cc1659e8dcfa00a550146bf3509c7cad8 M	lib
:040000 040000 8c81faa789cd54cd8a086ba6fb30db0b5b9174ce ec5b7d085be452fe798dea064d37140850cda45d M	spec
```

Hope that helps a little!

**Comment by rmosolgo** [comment]
Thanks for pointing that out! I wonder what _caused_ it 🤔 🤔

**Comment by celsworthtf** [comment]
Indeed, therein lies the rub :) I've been trying to work that out today with a git bisect:

```
iMac:~/graphql-ruby> git bisect bad 41e199caaec24b06a231131c3d57d29175ac23b1
iMac:~/graphql-ruby> git bisect good c9c8dce0bac1af7d8f2f3938e8cd54fd4f25292a
Bisecting: 140 revisions left to test after this (roughly 7 steps)
^[[A[f48a2591d17188e64dadc5cb70f7da3e240625f9] Merge branch 'master' into 1.10-dev
iMac:~/graphql-ruby> git bisect run ruby ../graphql-bug.rb
running ruby ../graphql-bug.rb
Bisecting: 73 revisions left to test after this (roughly 6 steps)
[727e211e9781fc7347582e7cf8503d9471aa7f93] implement class-based .find
running ruby ../graphql-bug.rb
Bisecting: 36 revisions left to test after this (roughly 5 steps)
[c0474aa90c964334b78859b32bb1bfe7c9358bd3] More fixes
running ruby ../graphql-bug.rb
Bisecting: 17 revisions left to test after this (roughly 4 steps)
[b4f14069e49fa6a5ae4b021deca88d5a16a31994] Fix schema printer
running ruby ../graphql-bug.rb
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[fb4898d4be6a6179ff1040d9b14866588e63c853] make some query_spec tests pass
running ruby ../graphql-bug.rb
Traceback (most recent call last):
	47: from ../graphql-bug.rb:53:in `<main>'
	46: from /Users/chris/graphql-ruby/lib/graphql/schema.rb:1189:in `execute'
	45: from /Users/chris/graphql-ruby/lib/graphql/schema.rb:1213:in `multiplex'
	44: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:49:in `run_all'
	43: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:59:in `run_queries'
	42: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
	41: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
	40: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
	39: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
	38: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
	37: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
	36: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
	35: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
	34: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
	33: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
	32: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
	31: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
	30: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
	29: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
	28: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:186:in `block in instrument_and_analyze'
	27: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
	26: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
	25: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:83:in `map'
	24: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
	23: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:112:in `begin_query'
	22: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter.rb:45:in `begin_query'
	21: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter.rb:72:in `evaluate'
	20: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
	19: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
	18: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
	17: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
	16: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:57:in `run_eager'
	15: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:118:in `evaluate_selections'
	14: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:118:in `each'
	13: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:203:in `block in evaluate_selections'
	12: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:344:in `resolve_with_directives'
	11: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:350:in `run_directive'
	10: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:344:in `block in resolve_with_directives'
	 9: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:205:in `block (2 levels) in evaluate_selections'
	 8: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
	 7: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
	 6: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
	 5: from /Users/chris/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:206:in `block (3 levels) in evaluate_selections'
	 4: from /Users/chris/graphql-ruby/lib/graphql/schema/field.rb:491:in `resolve'
	 3: from /Users/chris/graphql-ruby/lib/graphql/schema/field.rb:635:in `with_extensions'
	 2: from /Users/chris/graphql-ruby/lib/graphql/schema/field.rb:506:in `block in resolve'
	 1: from /Users/chris/graphql-ruby/lib/graphql/schema/field.rb:506:in `public_send'
/Users/chris/graphql-ruby/lib/graphql/schema/relay_classic_mutation.rb:35:in `resolve_with_support': undefined method `to_kwargs' for {:attributes=>{:person_id=>"abc"}}:Hash (NoMethodError)
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[5466ca2ff561dcd01cf53eb8d58c7d0c9cf950d8] update some more type methods
running ruby ../graphql-bug.rb
Bisecting: 2 revisions left to test after this (roughly 1 step)
[5932ef3fc8c9d26df1fb597a977093dcd9fb16ab] Update more runtime stuff
running ruby ../graphql-bug.rb
Traceback (most recent call last):
	38: from ../graphql-bug.rb:53:in `<main>'
	37: from /Users/chris/graphql-ruby/lib/graphql/schema.rb:1172:in `execute'
	36: from /Users/chris/graphql-ruby/lib/graphql/schema.rb:1196:in `multiplex'
	35: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:49:in `run_all'
	34: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:59:in `run_queries'
	33: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
	32: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
	31: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
	30: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
	29: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
	28: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
	27: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
	26: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
	25: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
	24: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
	23: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
	22: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
	21: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
	20: from /Users/chris/graphql-ruby/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
	19: from /Users/chris/graphql-ruby/lib/graphql/execution/multiplex.rb:185:in `block in instrument_and_analyze'
	18: from /Users/chris/graphql-ruby/lib/graphql/analysis/ast.rb:31:in `analyze_multiplex'
	17: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
	16: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
	15: from /Users/chris/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
	14: from /Users/chris/graphql-ruby/lib/graphql/analysis/ast.rb:32:in `block in analyze_multiplex'
	13: from /Users/chris/graphql-ruby/lib/graphql/analysis/ast.rb:32:in `map'
	12: from /Users/chris/graphql-ruby/lib/graphql/analysis/ast.rb:33:in `block (2 levels) in analyze_multiplex'
	11: from /Users/chris/graphql-ruby/lib/graphql/query.rb:252:in `valid?'
	10: from /Users/chris/graphql-ruby/lib/graphql/query/validation_pipeline.rb:35:in `valid?'
	 9: from /Users/chris/graphql-ruby/lib/graphql/query/validation_pipeline.rb:80:in `ensure_has_validated'
	 8: from /Users/chris/graphql-ruby/lib/graphql/query.rb:216:in `variables'
	 7: from /Users/chris/graphql-ruby/lib/graphql/query.rb:381:in `with_prepared_ast'
	 6: from /Users/chris/graphql-ruby/lib/graphql/query.rb:217:in `block in variables'
	 5: from /Users/chris/graphql-ruby/lib/graphql/query.rb:217:in `new'
	 4: from /Users/chris/graphql-ruby/lib/graphql/query/variables.rb:19:in `initialize'
	 3: from /Users/chris/graphql-ruby/lib/graphql/query/variables.rb:19:in `each_with_object'
	 2: from /Users/chris/graphql-ruby/lib/graphql/query/variables.rb:19:in `each'
	 1: from /Users/chris/graphql-ruby/lib/graphql/query/variables.rb:38:in `block in initialize'
/Users/chris/graphql-ruby/lib/graphql/schema/non_null.rb:47:in `coerce_input': undefined method `coerce_input' for #<Class:0x00007f8ab11e02b0> (NoMethodError)
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[45da333d9f2d0b44d525d609baddcf44708652a0] Update more runtime code
running ruby ../graphql-bug.rb
5932ef3fc8c9d26df1fb597a977093dcd9fb16ab is the first bad commit
commit 5932ef3fc8c9d26df1fb597a977093dcd9fb16ab
Author: Robert Mosolgo <rdmosolgo@gmail.com>
Date:   Wed Jul 17 11:20:23 2019 -0400

    Update more runtime stuff

:040000 040000 f8aa4264a155744b8b7167130987ed30384b4241 2a97058cc1659e8dcfa00a550146bf3509c7cad8 M	lib
:040000 040000 8c81faa789cd54cd8a086ba6fb30db0b5b9174ce ec5b7d085be452fe798dea064d37140850cda45d M	spec
bisect run success
```

But the errors reported when it finishes seem unrelated, maybe I hit a bad commit for some other reason, so I'm not sure how helpful that is.

Would you agree it's a bug though and the behaviour *should* be as 1.10.0pre1?

**Comment by rmosolgo** [comment]
> _should_ be as 1.10.0pre1?

Yes, I agree!

**Comment by rmosolgo** [comment]
It looks like it's particularly a mis-handling of _variables_, because I changed the `execute` call to use literal values and it _worked_: 

```ruby
Schema.execute(query: 'mutation { testMutation(input: { attributes: { personId: 1 } } ) }')
```

I think it must be around here: 

https://github.com/rmosolgo/graphql-ruby/compare/v1.10.0.pre1...v1.10.0.pre2#diff-e93b48ad28511014b5c2ba266dcc3db0R464

**Comment by rmosolgo** [comment]
I think _this_ call is a mistake: 

https://github.com/rmosolgo/graphql-ruby/blob/55265862420b545cbdac89c99383bf91261b4846/lib/graphql/execution/interpreter/runtime.rb#L521

It takes a variable value _as given_ and passes it along. But, that means that the given variable value is never recursively handled, so nested objects aren't properly wrapped. 

I'm not sure how to fix it yet, though.

**Comment by rmosolgo** [comment]
Well, I tried this again on 1.10.2, because I changed variable loading a bit, but it's broken in yet a _different_ way: 

```ruby
{"errors"=>[{"message"=>"Variable $input of type TestMutationInput! was provided invalid value", "locations"=>[{"line"=>1, "column"=>10}], "extensions"=>{"value"=>{"attributes"=>{"personId"=>"1"}}, "problems"=>[{"path"=>[], "explanation"=>"No object found for `personId: \"1\"`"}]}}]}
```

**Comment by DanAndreasson** [comment]
> Well, I tried this again on 1.10.2, because I changed variable loading a bit, but it's broken in yet a _different_ way:
> 
> ```ruby
> {"errors"=>[{"message"=>"Variable $input of type TestMutationInput! was provided invalid value", "locations"=>[{"line"=>1, "column"=>10}], "extensions"=>{"value"=>{"attributes"=>{"personId"=>"1"}}, "problems"=>[{"path"=>[], "explanation"=>"No object found for `personId: \"1\"`"}]}}]}
> ```
I'm also running into this. Do you have a solution in mind?

**Comment by rmosolgo** [comment]
Ok, I spent some time working with input coercion and opened #2729 , but I don't think that's actually the issue here. 

In fact, I think the issue here is that in 1.10.0.pre2, we changed how we implement `schema.possible_types(t)`. _Previously_, if `t` was an object type, we returned `[t]`. _Now_, we only return `[t]` _if `t` is present in the schema_. That is, if `t` is _hidden_, we don't return it. 

If a type isn't used as a member of a union or the return type of a field, it's not part of a schema. 

So, I was able to fix the provided test by _connecting_ `PersonType` to the schema: 

```diff 
  class QueryRoot < GraphQL::Schema::Object
+   field :p, PersonType, null: false
  end
```

Then, it ran fine, even on 1.10.2: 

```ruby
~/code/graphql-ruby $ ruby test.rb
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"testMutation"=>true}}>
```

So, although a bit confusing, I think it _was_ doing the right thing. (I'm trying to figure out how to share more info for debugging cases like this without disclosing the existence of hidden parts of the schema, #2286)

Please let me know if a solution like that doesn't work for you!

**Comment by DanAndreasson** [comment]
@rmosolgo so I just found out that there was a line snakecasing all incoming json in the application controller..
