### ISSUE TITLE
1.13.7+ broken on Ruby 2.5

### ISSUE THREAD

**Issue by evgeni** [rmosolgo/graphql-ruby#4073]
**Describe the bug**

When loading `graphql` (via `require 'graphql'`), an error is raised:
```
graphql-1.13.12/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
```

This happens only on Ruby 2.5. Ruby 2.7 is OK (and I did not test 2.6)

**Versions**

`graphql` version: 1.13.12 (actually, any 1.13.z starting with 1.13.7)
`rails` (or other framework): N/A
other applicable versions (`graphql-batch`, etc): N/A

**GraphQL schema**

N/A

**GraphQL query**

N/A

**Steps to reproduce**

```console
$ cat Gemfile
source 'https://rubygems.org'
gem 'graphql', '~> 1.13.0'

$ bundle install

$ cat test.rb 
require 'graphql'

$ bundle exec ruby ./test.rb
…
graphql-1.13.12/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
```

**Expected behavior**

The gem can be loaded ;-)

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
Traceback (most recent call last):
	16: from ./test.rb:1:in `<main>'
	15: from ./test.rb:1:in `require'
	14: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql.rb:114:in `<top (required)>'
	13: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql.rb:114:in `require'
	12: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema.rb:51:in `<top (required)>'
	11: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema.rb:51:in `require'
	10: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/relay_classic_mutation.rb:4:in `<top (required)>'
	 9: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/relay_classic_mutation.rb:5:in `<module:GraphQL>'
	 8: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/relay_classic_mutation.rb:23:in `<class:Schema>'
	 7: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/relay_classic_mutation.rb:25:in `<class:RelayClassicMutation>'
	 6: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/mutation.rb:71:in `field'
	 5: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/resolver/has_payload_type.rb:54:in `field'
	 4: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/member/has_fields.rb:12:in `field'
	 3: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/field.rb:129:in `from_options'
	 2: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/field.rb:129:in `new'
	 1: from /usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/member/accepts_definition.rb:154:in `initialize'
/usr/share/gems/gems/graphql-1.13.12/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
```

</details>

**Additional context**

The same seems to work fine with 1.12.24, 1.13.6 (and older 1.13.z) and 2.0.7

The problem seems to be that `arguments`, `extensions` and `directives` end up being `nil` instead of `EMPTY_HASH`/`EMPTY_ARRAY` or actual content.

**Comment by evgeni** [comment]
Yeah, I'm in the process to upgrade from 1.8 😅

Maybe going to 2.0 is the best here, but that currently doesn't work.
