### ISSUE TITLE
undefined method `each' for #<Concurrent::Map:0x007fbbe43a2670 entries=0 default_proc=nil>

### ISSUE THREAD

**Issue by brilyuhns** [rmosolgo/graphql-ruby#664]
`Schema.execute(query)` does not seem to work with `concurrent-ruby(v1.0.2)`. Had to upgrade `concurrent-ruby(v1.0.5)`

Is there a way to mention the version of an **optional** dependency? 

```shell

NoMethodError - undefined method `each' for #<Concurrent::Map:0x007fbbe43a2670 entries=0 default_proc=nil>:
  graphql (1.5.5) lib/graphql/execution/lazy/lazy_method_map.rb:46:in `find_superclass_method'
  graphql (1.5.5) lib/graphql/execution/lazy/lazy_method_map.rb:36:in `block in get'
  concurrent-ruby (1.0.2) lib/concurrent/collection/map/non_concurrent_map_backend.rb:31:in `compute_if_absent'
  concurrent-ruby (1.0.2) lib/concurrent/collection/map/mri_map_backend.rb:25:in `block in compute_if_absent'
  concurrent-ruby (1.0.2) lib/concurrent/collection/map/mri_map_backend.rb:25:in `synchronize'
  concurrent-ruby (1.0.2) lib/concurrent/collection/map/mri_map_backend.rb:25:in `compute_if_absent'
  graphql (1.5.5) lib/graphql/execution/lazy/lazy_method_map.rb:36:in `get'
  graphql (1.5.5) lib/graphql/schema.rb:390:in `lazy_method_name'
  graphql (1.5.5) lib/graphql/schema.rb:395:in `lazy?'
  graphql (1.5.5) lib/graphql/execution/execute.rb:73:in `resolve_field'
  graphql (1.5.5) lib/graphql/execution/execute.rb:31:in `block in resolve_selection'
  graphql (1.5.5) lib/graphql/execution/execute.rb:30:in `each'
  graphql (1.5.5) lib/graphql/execution/execute.rb:30:in `resolve_selection'
  graphql (1.5.5) lib/graphql/execution/execute.rb:10:in `execute'
  graphql (1.5.5) lib/graphql/query/executor.rb:37:in `execute'
  graphql (1.5.5) lib/graphql/query/executor.rb:18:in `result'
  graphql (1.5.5) lib/graphql/query.rb:125:in `result'
  graphql (1.5.5) lib/graphql/schema.rb:203:in `execute'
  app/controllers/graphql_controller.rb:10:in `query'
```

**Comment by rmosolgo** [comment]
Sorry for that! Poor testing of the new feature on my part. It will be fixed by #663 in the next release. Thanks for reporting this!
