### ISSUE TITLE
Circular dependency for interface type. Works with proc in versions up to 1.9.18, but breaks in newer versions.

### ISSUE THREAD

**Issue by MartinManev** [rmosolgo/graphql-ruby#2716]
Hi. I'm not using rails and need to define an interface type.

My interface type looks something like this:
```
# require everything ...

module User
  include Types::Interface

  definition_methods do
    def resolve_type(object, context)
      if object.is_a?(BasicUser)
        Types::BasicUser
      elsif object.is_a?(AdminUser)
        Types::AdminUser
      else
        raise 'something'
      end
    end
  end

  orphan_types Types::BasicUser, Types::AdminUser
end
```

And my implementing types are defined like so:
```
# require everything ...

module Types
  class BasicUser < Types::Object
    implements ->{ Types::User }
  end
end
```

In the previous version of this gem I couldn't just write `implements Types::User` (not a proc), because I would create a circular dependency. That is why I wrapped the type in a proc and it worked. However, with the latest version (1.10.2) this doesn't work anymore. I get the following error:
```
undefined method `graphql_name' for #<Proc:0x00005575792a0848> (NoMethodError)
```
I saw that there are other issues where it is suggested that types should be defined as strings to avoid this problem, but it doesn't seem to work for my case. Is there anything else I could try?

**Comment by MartinManev** [comment]
If I remove the reference to the interface from the implementing types:
```
module Types
  class BasicUser < Types::Object
  end
end
```

... and put the following lines below the interface definition:
```
module User
  # ...
end

Types::BasicUser.implements(Types::User)
Types::AdminUser.implements(Types::User)
```

Then the problem is solved. Any other alternatives?

**Comment by rmosolgo** [comment]
What happens if you remove the proc? Does it raise an error, or does it fail some way? (I wouldn't be surprised if it just worked in the new version of GraphQL-Ruby.)

>  other alternatives

Yes, you can also use strings that name the Ruby class. That defers loading a tiny bit. For example: 

```ruby 
orphan_types "Types::User", ...
```

**Comment by MartinManev** [comment]
Hi, @rmosolgo 

> What happens if you remove the proc? Does it raise an error, or does it fail some way? (I wouldn't be surprised if it just worked in the new version of GraphQL-Ruby.)

Removing the proc leads to `<COMPLETELY WRONG MODULE> cannot be implemented since it's not a GraphQL Interface. Use 'include' for plain Ruby modules. (RuntimeError)`. It just silently fails to load the correct module, but it is definitely a problem with circular dependencies.

> Yes, you can also use strings that name the Ruby class. That defers loading a tiny bit. For example:
> > orphan_types "Types::User", ...

That doesn't work for me in this case.

Anyway, I have since solved the problem by moving the problematic requires and circular references outside the type definitions. It is OK to close the issue unless you plan to do something about the proc.
