### ISSUE TITLE
Getting undefined method `arguments' in extract_deprecated_arguments

### ISSUE THREAD

**Issue by digitalmoksha** [rmosolgo/graphql-ruby#4056]
**Describe the bug**

A subclass of `GraphQL::Schema::InputObject` is used as an argument in one of our resolvers, like this:

```ruby
argument :timeframe, Types::TimeframeInputType,
         required: false,
         description: 'List items overlapping the given timeframe.'


module Types
  class TimeframeInputType < GraphQL::Schema::InputObject
    graphql_name 'Timeframe'
    description 'A time-frame defined as a closed inclusive range of two dates'
    
    argument :start, ::Types::DateType, required: true, description: 'Start of the range.'
    argument :end, ::Types::DateType, required: true, description: 'End of the range.'

    def prepare
      if self[:end] && self[:start] && self[:end] < self[:start]
        raise ::Gitlab::Graphql::Errors::ArgumentError, 'start must be before end'
      end

      to_h
    end
  end
end
```

This worked fine on `1.11.x`, but now on `1.13.12`, I'm getting

```
undefined method `arguments' for {:start=\u003eSat, 30 Apr 2022, :end=\u003eMon, 02 May 2022}:Hash
```

I've traced it down to

```ruby
            if argument.definition.type.kind.input_object?
              extract_deprecated_arguments(argument.value.arguments.argument_values) # rubocop:disable Development/ContextIsPassedCop -- runtime args instance
```

in https://github.com/rmosolgo/graphql-ruby/blob/1f8b198e00f69b08b9cd7eee00a799c4a304033b/lib/graphql/analysis/ast/field_usage.rb#L42

I think if we checked for `respond_to?(:arguments)` like is done in the `list?` branch, it would fix this. It does when I make the change locally.

```ruby
            if argument.definition.type.kind.input_object? && argument.value.respond_to?(:arguments)
              extract_deprecated_arguments(argument.value.arguments.argument_values) # rubocop:disable Development/ContextIsPassedCop -- runtime args instance
```

**Versions**

`graphql` version: 1.13.12
`rails` (or other framework): Rails 6.1.4.7

**Query**

```
{
  group(fullPath: "group1/group2"){
    milestones(timeframe: {start: "2022-05-04", end: "2022-05-06"}){
      edges {
        node {
          id
          title
          state
        }
      }
    }
  }
}
```

**Comment by rmosolgo** [comment]
I'm curious how the input object was transformed into 

```ruby
{:start=>Sat, 30 Apr 2022, :end=>Mon, 02 May 2022}
```

Is there a `prepare` implementation that returns a hash? Or were values passed in by variables?

**Comment by digitalmoksha** [comment]
🤔 You're right, there is a `prepare` that returns a hash:

```ruby
    def prepare
      if self[:end] && self[:start] && self[:end] < self[:start]
        raise ::Gitlab::Graphql::Errors::ArgumentError, 'start must be before end'
      end

      to_h
    end
```

I've added that, and the query, into the description above.

---

So here are some different scenarios I tried:

- return a hash from the `prepare`, I get the reported error
- return nothing from `prepare`, I get the same error, which makes sense
- return `self` from `prepare`, as shown in the [docs](https://graphql-ruby.org/api-doc/2.0.7/GraphQL/Schema/InputObject.html#prepare-instance_method), and the resolver receives the complete input object, rather than a hash as I intuitively expected:

  ```ruby
  => {:timeframe=>
  #<Types::TimeframeInputType:0x00007f9fbc797968
   @arguments=#<GraphQL::Execution::Interpreter::Arguments @keyword_arguments={:start=>Wed, 04 May 2022, :end=>Fri, 06 May 2022}>,
   @context=#<Query::Context ...>,
   @maybe_lazies=[],
   @ruby_style_hash={:start=>Wed, 04 May 2022, :end=>Fri, 06 May 2022}>,
   :sort=>:due_date_asc}
  ```

  I verified that in our un-upgraded code, returning `self` (or removing `prepare` completely), also gives the input object

So it looks like we're actually using it wrong.  Not sure why we did it that way, other than we're used to getting a plain hash for args in the resolver.  I'll update our code to grab the hash in the resolver.

**Comment by mcelicalderon** [comment]
@rmosolgo is this the intended behavior? From the docs I see that we should actually be able to use prepare to return a different ruby object? https://graphql-ruby.org/type_definitions/input_objects#converting-to-other-ruby-objects

In the example, a range is returned using two arguments from the input object

**Comment by rmosolgo** [comment]
Yeah, I think a check for `.respond_to?(:arguments)` is in order, or perhaps some other way to get the AST/variables value instead of using the prepared value.

**Comment by severin** [comment]
I'm also running into this issue: we have a input object with a `prepare` implementation that returns a hash and a subclass of `FieldUsage` that reports deprecated fields.

Would be great to have this reopened and fixed @rmosolgo
