### ISSUE TITLE
EmptyScopedContext missing current_path method in version 2.0.18 

### ISSUE THREAD

**Issue by lyricsboy** [rmosolgo/graphql-ruby#4373]
**Describe the bug**

We have a cache control implementation that relies on accessing `context.scoped_context.current_path` in a method on our `class BaseObject < GraphQL::Schema::Object` in order to do its thing. When updating to 2.0.18, our integration tests for this started raising exceptions.

**Versions**

`graphql` version: 2.0.18
`rails` (or other framework): 6.1, 7.0
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

TBD

**GraphQL query**

TBD

**Expected behavior**

The value of `current_path` is available when requested.

**Actual behavior**

The EmptyScopedContext module does not have a `current_path` method.

```
ERROR: undefined method `current_path' for GraphQL::Query::Context::EmptyScopedContext:Module

          current_path = context.scoped_context.current_path
                                               ^^^^^^^^^^^^^
```

**Additional context**

This change was introduced in #4342 

Should this EmptyScopedContext module be initialized in some way? An instance of a class? Should it have a `current_path` method?

**Comment by rmosolgo** [comment]
Oh, interesting! Sorry for the trouble, I didn't know there were any public uses of that method. I can take care to put it back for that empty context object. (`EmptyScopedContext` will have to be re-implemented as a class which is initialized with its backing `context` object, then `def current_path` would return `context[:current_path]`.)

**Comment by rmosolgo** [comment]
Sorry again for the trouble. I just merged #4376 which _should_ fix this issue. Could you give `master` a try with your app and see if it works for you? If it does, I'll release a new version. You can point your gemfile to master like this:


```
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "master"
```
