### ISSUE TITLE
Couldn't resolve field 'edges' to GraphQL::Relay::RelationConnection

### ISSUE THREAD

**Issue by gauravtiwari** [rmosolgo/graphql-ruby#101]
Hello @rmosolgo 

Getting following error when fetching next set of records using `first: 10` parameter in Relay. 

### Error when fetching next posts (pagination)
``` ruby
 RuntimeError (Couldn't resolve field 'edges' to GraphQL::Relay::RelationConnection '#<GraphQL::Relay::RelationConnection:0x007ff75a0ff150>' (resulted in undefined method `engine' for #<Arel::Table:0x007ff759587a20>)):
11:16:11 web.1    |   app/controllers/graphql_controller.rb:8:in `create'
11:16:11 web.1    |   lib/graphql_reloader.rb:10:in `call'
```
This works in previous versions of the Gem (0.10.8), but not in the recent version. 

### Gems used
``` bash
Latest version of graphql and graphql-relay
Rails version 5 beta
```

**Comment by rmosolgo** [comment]
Oh! It looks like we don't support Rails 5 here, where we're trying to cast a string to the proper data type: 

https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L79-L83

(It was added to properly cast dates)

**Comment by gauravtiwari** [comment]
Hey! this makes sense. I kind of doubted that it's a Rails 5 related - as a lot has changed. Perhaps we could work to support AR5?

**Comment by kristianm** [comment]
I introduced the type casting to RelationConnection, didn't think about rails 5 at the time.
But they seem to have [changed it quite recently](https://github.com/rails/rails/commit/158c7eb1d61a28452e0aafd1e05314352eea2749#diff-ece1d9e4cf3db41b2c394e2acfcc2330), I'm trying to see how we could adapt it to AR5.

**Comment by kristianm** [comment]
[This should fix it](https://github.com/rmosolgo/graphql-relay-ruby/pull/26)

Perhaps we should add AR5 to the tests. I did it locally just to verify.

**Comment by gauravtiwari** [comment]
Awesome @kristianm this works :+1:
