### ISSUE TITLE
Unable to use field instrumenter

### ISSUE THREAD

**Issue by pyeremenko** [rmosolgo/graphql-ruby#1897]
I can't find a way how to use field instrumenter after upgrading the gem to 1.8.8

```ruby
gem 'graphql', '~> 1.8.8'
gem 'graphql-batch', '~> 0.3.3'
gem 'graphql-guard', '~> 1.1.0'
```

I'll show an example using the very simple app with no other gems and the only model and GraphQL type.

Schema:

```ruby
GraphQL::Field.accepts_definitions test: GraphQL::Define.assign_metadata_key(:test)

class GqltestSchema < GraphQL::Schema
  instrument(:field, Instruments::FieldShufflingInstrumentation.new)
  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

Type:

(the old approach works)

```ruby
Types::LinkType = GraphQL::ObjectType.define do
  field :description, !types.String do
    test_instrument
  end
end
```

but the new one doesn't

```ruby
module Types
  class LinkType < GraphQL::Schema::Object
    field :description, String, null: false do
      test_instrument
    end
  end
end
```

It says:

```
undefined local variable or method test_instrument for #<GraphQL::Schema::Field:0x00007f556c7ed560>`
```

It's intertesting, that the guide explains everything: attaching to schema, definition of the instrumenter but not adding it to an actual field http://graphql-ruby.org/fields/instrumentation.html

**Comment by rmosolgo** [comment]
You have to reimplement `test_instrument` as a method on your base field, you can find some notes about compatibility between old and new here: http://graphql-ruby.org/type_definitions/extensions.html#customizing-fields

**Comment by rmosolgo** [comment]
I hope that worked for you!
