### ISSUE TITLE
undefined method `validate_directive_argument' when upgrade graphql-ruby 1.11 to 1.12 version

### ISSUE THREAD

**Issue by marcuxyz** [rmosolgo/graphql-ruby#4725]
I'm trying to upgrade `graphql-ruby 1.11 to 1.12 ` , but, when I run the tests I give this error:

`undefined method `validate_directive_argument' for #`

Has anyone gotten this yet?

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble. Please share the full error message and backtrace if you'd like to look into this together.

**Comment by marcuxyz** [comment]
Thanks @rmosolgo  the problem occurred because of the `search_object_graphql` gem.
