### ISSUE TITLE
Can't get total count of connection (excluding pagination)

### ISSUE THREAD

**Issue by nicolasrouanne** [rmosolgo/graphql-ruby#2829]
**Describe the bug**

When trying to get the `total_count` of a connection, I get only the number of results filtered by the pagination, not the number of objects in the connection.

**Versions**

`graphql`: 1.10.3
`rails` : 6.0.2.1
`graphql-batch`: 0.4.2

**GraphQL schema**
```ruby
class Types::BaseConnection < GraphQL::Types::Relay::BaseConnection
  field :total_count, Integer, null: false

  def total_count
    object.nodes&.count
  end
end

class Types::BaseObject < GraphQL::Schema::Object
  field_class Types::BaseField
  connection_type_class BaseConnection
end

class Types::QueryType < Types::BaseObject
  add_field(GraphQL::Types::Relay::NodeField)
  field :users, UserType.connection_type, null: false

  def users
    User.all
  end
end


class ApiSchema < GraphQL::Schema
  query(Types::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections
end
```

**GraphQL query**
When querying with no pagination parameters, I get the correct amount of objects in `totalCount`, i.e. all the objects

```graphql
query {
    users {
        totalCount
        nodes {
            id
        }
    }
}
```

```json
{
    "data": {
        "users": {
            "totalCount": 5,
            "nodes": [
                {
                    "id": "U2FpbG9yLTI="
                },
                {
                    "id": "U2FpbG9yLTM="
                },
                {
                    "id": "U2FpbG9yLTQ="
                },
                {
                    "id": "U2FpbG9yLTc="
                },
                {
                    "id": "U2FpbG9yLTEw"
                }
            ]
        }
    }
}
```

When passing pagination parameters the `totalCount` doesn't reflect the entire connection, rather the current page
```graphql
query {
    users(first: 2) {
        totalCount
        nodes {
            id
        }
    }
}
```

```json
{
    "data": {
        "users": {
            "totalCount": 2,
            "nodes": [
                {
                    "id": "U2FpbG9yLTI="
                },
                {
                    "id": "U2FpbG9yLTM="
                }
            ]
        }
    }
}
```

**Expected behavior**

I expected `total_count` to return the total number of items in the connection, as pointed out in [that wiki article](https://github.com/rmosolgo/graphql-ruby/wiki/How-To:-Set-a-Custom-Base-Connection-class-to-provide-totalCount-and-totalPageCount-fields-on-all-Connections)

**Actual behavior**

It only returns the number of items in a page.

**Comment by rmosolgo** [comment]
Thanks for opening this issue -- that doc is out-of-date, and I haven't written a better replacement yet 😖 . In the new pagination system in 1.10+, the methods  of connection objects have changed. 

- `items` contains the "raw" collection object returned from application code (for example, a whole Array or an unpaginated ActiveRecord::Relation) 
- `nodes` contains the paginated items. This value will be `nodes { ... }` (or `edges { node { ... } }`) in the GraphQL result 

So, you code could be updated like this: 

```diff 
  def total_count
+   object.items&.count
-   object.nodes&.count
  end
```

Does that work for you? 

Let's keep this open til I fix that doc.

**Comment by nicolasrouanne** [comment]
Using `object.items&.count` works perfectly! 😃🎉
Thanks for the quick reply 🙏 

I would find it very useful indeed to know more generally what are the available methods to call (be it in `Types`, `Connection`, `Edge`, etc.). For instance, knowing that you can access `object` or `items` is not very easy to find, as you say. 
> It would be great if that could be added to [the guides](https://graphql-ruby.org/guides), which I find very useful and readable compared to the [_RubyDoc_](https://graphql-ruby.org/api-doc) 🙈

**Comment by POPPIN-FUMI** [comment]
I did the same conf with

Ruby 3.0.0
Sinatra 6.1.3

but countAll doesn't show up in graphql playground document.
Does any one know how its working with ruby 3.0.0?

**Comment by codefist** [comment]
total_count should be there by default

**Comment by angeloocana** [comment]
`object.items.size` is not working for me anymore, I get the error:
```
undefined method `items' for #<GraphQL::Pro::RelationConnection::OrderedRelationConnection:0x00007efc2fd66ff0 
```

**Comment by rmosolgo** [comment]
Hey @angeloocana, could you please open a new issue (https://github.com/rmosolgo/graphql-ruby/issues/new/choose) for the problem you encountered? I'd like to understand what you were working on (or what else changed) when your code stopped working for you, but it looks like your situation is a bit different than the one described here last year.
