### ISSUE TITLE
undefined method `each' for nil:NilClass (NoMethodError) after upgrading to 1.13.7 from 1.13.6

### ISSUE THREAD

**Issue by sebasjimenez10** [rmosolgo/graphql-ruby#4076]
**Describe the bug**

When updating from 1.13.6 to 1.13.7 a build error occurred, more specifically as follows:
```
/Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/member/accepts_definition.rb:154:in `initialize'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:129:in `new'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:129:in `from_options'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/member/has_fields.rb:12:in `field'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/resolver/has_payload_type.rb:54:in `field'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/mutation.rb:71:in `field'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:25:in `<class:RelayClassicMutation>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:23:in `<class:Schema>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:5:in `<module:GraphQL>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:4:in `<top (required)>'
```
I started debugging the gem code and found that when calling `new` from `from_options` the default value for the argument `arguments` was not being properly assigned. I went ahead and assigned `EMPTY_HASH` to it, but this didn't fix the issue as another one came up. See the related code below:

```ruby
# lib/graphql/schema/field.rb
...
def self.from_options(name = nil, type = nil, desc = nil, resolver: nil, mutation: nil, subscription: nil,**kwargs, &block)
  ...
  new(**kwargs, &block)
end
```
```ruby
# lib/graphql/schema/field.rb
...
def initialize(type: nil, name: nil, owner: nil, null: true, field: nil, function: nil, description: nil, deprecation_reason: nil, method: nil, hash_key: nil, dig: nil, resolver_method: nil, resolve: nil, connection: nil, max_page_size: :not_given, scope: nil, introspection: false, camelize: true, trace: nil, complexity: 1, ast_node: nil, extras: EMPTY_ARRAY, extensions: EMPTY_ARRAY, connection_extension: self.class.connection_extension, resolver_class: nil, subscription_scope: nil, relay_node_field: false, relay_nodes_field: false, method_conflict_warning: true, broadcastable: nil, arguments: EMPTY_HASH, directives: EMPTY_HASH, validates: EMPTY_ARRAY, legacy_edge_class: nil, &definition_block)
  ...
  arguments.each do |name, arg| # <= error happening here (line 282)
    ...
  end
end
```
I haven't been able to upgrade from `1.13.6` and we're now at `1.13.12` I don't want to get too far behind. Does anyone have any idea on how to resolve this? Thanks so much in advance! 🙏 

**Versions**

`graphql` version: `1.13.6`
`rails` (or other framework): `5.2.4.3`
other applicable versions (`graphql-batch`, etc):
- `graphql-batch` version: `0.5.1`
- `apollo-federation` version: `3.0.0`
- `apollo_upload_server` version: `2.1.0`
- `apollo-tracing` version: `1.6`

ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [-darwin21]`

For the record I remove the usage from the last three gems`apollo-federation`, `apollo_upload_server` and `apollo-tracing` to make sure none of these were influencing this outcome and they weren't

**GraphQL schema**

```ruby
class Schema < GraphQL::Schema
  include ApolloFederation::Schema

  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::Batch
  use GraphQL::Tracing::DataDogTracing
  use ApolloTracing.new if Rails.env.development?
end

```

**Steps to reproduce**

Just trying to run the rails console will trigger the error

**Expected behavior**

Rails app to be able to boot properly

**Actual behavior**

The error described above

**Additional context**

I tried looking at the diff between the two versions but nothing stood up since I'm not too familiar with the internals: https://github.com/rmosolgo/graphql-ruby/compare/v1.13.6...v1.13.7

<details>
  <summary>Complete exception stack trace</summary>
  
  ```
/Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/member/accepts_definition.rb:154:in `initialize'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:129:in `new'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/field.rb:129:in `from_options'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/member/has_fields.rb:12:in `field'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/resolver/has_payload_type.rb:54:in `field'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/mutation.rb:71:in `field'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:25:in `<class:RelayClassicMutation>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:23:in `<class:Schema>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:5:in `<module:GraphQL>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema/relay_classic_mutation.rb:4:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql/schema.rb:51:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.13.7/lib/graphql.rb:113:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/apollo-federation-3.0.0/lib/apollo-federation/entities_field.rb:3:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/apollo-federation-3.0.0/lib/apollo-federation/schema.rb:3:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/apollo-federation-3.0.0/lib/apollo-federation.rb:4:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/sebasjimenez/dev/envoy/envoy-graphql-ruby/config/application.rb:9:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
        from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/sebasjimenez/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

</details>

**Comment by sebasjimenez10** [comment]
I found out that if I move `dig: nil,` in the method signature from where it is to after `validates: EMPTY_ARRAY` this leads me to suspect that there is some internal messing the parameters somewhere.

**Comment by sebasjimenez10** [comment]
Another piece of evidence is that this is the field that triggers the error I am experiencing:
```
#<GraphQL::Schema::Field clientMutationId: String>
String
:client_mutation_id
GraphQL::Schema::RelayClassicMutation
```
These are the `class`, `type`, `name` and `owner`

**Comment by sebasjimenez10** [comment]
Apologies for the spamy issue here, I was able to figure out. This was related to my current ruby version, I upgraded to `2.7.6` and the issue went away. Closing.
