### ISSUE TITLE
v2.0.19: undefined method `platform_authorized'

### ISSUE THREAD

**Issue by mroach** [rmosolgo/graphql-ruby#4393]
**Describe the bug**

After upgrading from 2.0.17 to 2.0.19, we started getting this error:

```
undefined method `platform_authorized' for #<#<Class:0x00007ff2acb71488>:0x00007ff295964328 @set_action_name=false, @trace_scalars=false, @platform_field_key_cache={}, @platform_authorized_key_cache={Types::QueryType=>"Query.authorized.graphql"}, @platform_resolve_type_key_cache={}, @multiplex=#<GraphQL::Execution::Multiplex:0x00007ff2959643c8 @schema=FrontendSchema, @queries=[query ...], @context={:backtrace=>nil, :tracers=>nil, :dataloader=>#<GraphQL::Dataloader:0x00007ff2959640f8 @source_cache={}, @pending_jobs=[]>, :interpreter_instance=>#<GraphQL::Execution::Interpreter:0x00007ff2959314c8>}, @current_trace=#<#<Class:0x00007ff2acb71488>:0x00007ff295964328 ...>, @dataloader=#<GraphQL::Dataloader:0x00007ff2959640f8 @source_cache={}, @pending_jobs=[]>, @tracers=[#<GraphQL::Pro::OperationStore::QueryInstrumentation:0x00007ff2acb71640 @operation_store=#<GraphQL::Pro::OperationStore:0x00007ff2acb71c80 @default_touch_last_used_at=true, @backend=#<GraphQL::Pro::OperationStore::ActiveRecordBackend:0x00007ff2acb71a50 @operation_store=#<GraphQL::Pro::OperationStore:0x00007ff2acb71c80 ...>>, @schema=FrontendSchema, @index=#<GraphQL::Pro::OperationStore::Index:0x00007ff2acb71988 @operation_store=#<GraphQL::Pro::OperationStore:0x00007ff2acb71c80 ...>, @backend=#<GraphQL::Pro::OperationStore::ActiveRecordBackend:0x00007ff2acb71a50 @operation_store=#<GraphQL::Pro::OperationStore:0x00007ff2acb71c80 ...>>>, @pending_last_used_ats={1588=>2023-03-21 09:30:57.258335464 UTC, 1261=>2023-03-21 09:30:58.552771607 UTC, 1726=>2023-03-21 09:30:59.350028189 UTC, 831=>2023-03-21 09:30:58.865814529 UTC}, @mutex=#<Thread::Mutex:0x00007ff2acb717f8>, @update_last_used_at_every=5, @ticker_thread=#<Thread:0x00007ff297b36d70 /usr/local/bundle/gems/graphql-pro-1.24.0/lib/graphql/pro/operation_store.rb:137 sleep>>>], @max_complexity=nil>, @query=nil>
Did you mean?  platform_authorized_key
               platform_authorized_lazy
```

**Versions**

`graphql`: 2.0.19
`graphql-pro`: 1.24.0
`graphql-enterprise`: 1.2.0
`appsignal`: 3.3.7
`rails`: 7.0.4.3
`ruby`: 3.1.2

**GraphQL schema**

We're using AppSignal tracing:

```ruby
use(GraphQL::Tracing::AppsignalTracing)
```

**Steps to reproduce**

Run any query.

**Expected behavior**

No crash.

**Actual behavior**

Crash. Any query results in a 500 with that error.

**Mitigation**

Reverted to 2.0.17 and the problem went away.

**Comment by rmosolgo** [comment]
Sorry, I missed a spot on the Appsignal Tracer migration! This should have been fixed by #4390 , could you give `master` a try: 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "master"
```

If it works for you, I'll go ahead and cut 2.0.20 with that fix.

**Comment by mroach** [comment]
Master works without a problem :)

**Comment by rmosolgo** [comment]
I think this particular issue was fixed previously, but then another one popped up (https://github.com/rmosolgo/graphql-ruby/issues/4387#issuecomment-1495580233) which was addressed in #4419. It should be fixed on master and soon-to-be-released 2.0.21!
