### ISSUE TITLE
Error with undefined method `types' for nil:NilClass when running rspec

### ISSUE THREAD

**Issue by geeknees** [rmosolgo/graphql-ruby#5040]
**Describe the bug**

I upgraded from 2.3.7 to 2.3.10 and when running rspec I encountered the error undefined method `types' for nil:NilClass. This may be intentional and not a bug, but I am unsure how to resolve it and have raised an issue. I would be happy to check.

**Versions**

`graphql` version: 2.3.10
`rails` (or other framework): 7.1.3.4
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
module Resolvers
  class Users < Resolvers::Base
    type ObjectTypes::User.connection_type, null: false

    description 'Find users by roles. You can pass XXX_role or [XXX_role, YYY_role].'

    argument :role, [EnumTypes::User::Role]

    def resolve(role:)
      if role&.include?('evaluation_role')
        User.evaluation_test_users
      elsif role&.include?('level_aptitude_role')
        User.level_aptitude_test_users
      else
        User.where(role: role)
      end
    end
  end
end
```

**rspec**

```ruby
require 'rails_helper'

RSpec.describe Resolvers::Users do
  describe '#resolve' do
    context 'when role includes evaluation_role' do
      it 'returns evaluation test users filtered by service' do
        user1 = create(:user, role: 'evaluation_role')
        user2 = create(:user, role: 'evaluation_role')
        allow(User).to receive(:evaluation_test_users).and_return([user1, user2])

        result = described_class.new(object: nil, field: nil, context: nil).resolve(role: ['evaluation_role'])

        expect(result).to contain_exactly(user1, user2)
      end
    end
  end
end
```

**Steps to reproduce**

Running rspec

**Expected behavior**

pass the test

**Actual behavior**

receive an error

```ruby
Failures:

  1) Resolvers::Users#resolve when role includes evaluation_test_teacher_role returns evaluation test users filtered by service
     Failure/Error: result = described_class.new(object: nil, field: nil, context: nil).resolve(role: ['evaluation_role'])

     NoMethodError:
       undefined method `types' for nil:NilClass
     # ./spec/graphql/resolvers/users_spec1.rb:11:in `new'
     # ./spec/graphql/resolvers/users_spec1.rb:11:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:80:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:79:in `block (2 levels) in <top (required)>'
```

**Additional context**

I encountered this error when upgrading from 2.3.7.
I assume that the following changes have been affected

https://github.com/rmosolgo/graphql-ruby/commit/db7a9bcaceb77dc0af78b73e0d5c2ad849c27598#diff-fdbf285d34242cb3cb7b1e56e80f5d39bc600246e72b7bb32190e555432f156cR39

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble and thanks for the detailed writeup. I think you're right about the change that caused this errors. 

Resolvers aren't supported outside of GraphQL queries (due to issues like this...). I can think of a couple of options: 

- Use the `run_graphql_field` helper instead, which provides full GraphQL context. See more: https://graphql-ruby.org/testing/helpers.html
- Or, create a dummy `Query::Context` instance to pass instead of `context: nil`. This is _also_ outside of GraphQL-Ruby's public API, but it will probably work for while. Like this: 
 
  ```ruby 
  query_ctx = GraphQL::Query.new(MySchema, "{ __typename }").context
  ```
  
  Then, pass `context: query_ctx` into the Resolver. 

How about giving one of those a try?

**Comment by geeknees** [comment]
Thank you for your prompt response. We have tried both responses. The latter would maintain the current test case, but we don't want to use the internal API, so we will use the former method.


```ruby
require 'rails_helper'

RSpec.describe Resolvers::Users, type: :graphql do
  describe '#resolve' do
    subject { run_graphql_field("Query.users", nil, arguments: { role: role }).items }

    let!(:user1) { create(:user, role: 'evaluation_role') }
    let!(:user2) { create(:user, role: 'evaluation_role') }

    context 'when role includes evaluation_role' do
      let(:role) { 'evaluation_role' }

      it {
        expect(subject).to eq [user2, user2]
      }
    end
  end
end
```

```ruby
require 'rails_helper'

RSpec.describe Resolvers::Users do
  describe '#resolve' do
    subject { resolver.resolve(role: role) }

    let(:query_ctx) { GraphQL::Query.new(TofflerSchema, "{ __typename }").context }
    let(:resolver) { described_class.new(object: nil, context: query_ctx, field: nil) }
    let!(:user1) { create(:user, role: 'evaluation_role') }
    let!(:user2) { create(:user, role: 'evaluation_role') }

    context 'when role includes evaluation_role' do
      let(:role) { 'evaluation_role' }

      it {
        expect(subject).to eq [user2, user1]
      }
    end
  end
end
```

Closed as resolved. Thank you very much.

**Comment by rmosolgo** [comment]
Glad it worked for you, thanks for sharing your solution :+1:

**Comment by Hareramrai** [comment]
Hey @rmosolgo,  We are facing some problems with initializing subclasses of `Types::BaseInputObject`. The above `query_ctx` suggestion doesn't work for us. 

```ruby

RSpec.describe Types::OrderInputType do
  let(:query_ctx) { GraphQL::Query.new(AppSchema, '{ __typename }').context }
  let(:input_type) do
    described_class.new(
      nil,
      ruby_kwargs: { title: 'title', description: 'description' },
      context: query_ctx,
      defaults_used: {}
    )
  end
end
```
It's failing from `2.3.8` only.

**Comment by rmosolgo** [comment]
@Hareramrai , I'd be happy to help you investigate, but I need more information about what's "failing." Does it raise an error? If so, please share the full error message and stack trace. Is the Rspec example failing? If so, please share the example code and the failure message. If it's failing in another way, please describe it with as much detail as you can.

**Comment by Hareramrai** [comment]
@rmosolgo, Thanks for replying, I was able to find the problem and it was related to the custom scalar type.
